//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opcs.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("opcs.Resources.CodeMessages", typeof(CodeMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Message.
        /// </summary>
        internal static string opcs_debug_test_message {
            get {
                return ResourceManager.GetString("opcs.debug.test_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username/email or password!.
        /// </summary>
        internal static string opcs_error_auth_login_failed {
            get {
                return ResourceManager.GetString("opcs.error.auth.login_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized!.
        /// </summary>
        internal static string opcs_error_auth_unauthorized {
            get {
                return ResourceManager.GetString("opcs.error.auth.unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the right to access this!.
        /// </summary>
        internal static string opcs_error_permission_forbidden_access {
            get {
                return ResourceManager.GetString("opcs.error.permission.forbidden_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password and password must be the same!.
        /// </summary>
        internal static string opcs_error_request_confirm_password_not_equal {
            get {
                return ResourceManager.GetString("opcs.error.request.confirm_password_not_equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty property!.
        /// </summary>
        internal static string opcs_error_request_empty_property {
            get {
                return ResourceManager.GetString("opcs.error.request.empty_property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found!.
        /// </summary>
        internal static string opcs_error_request_invalid_endpoint {
            get {
                return ResourceManager.GetString("opcs.error.request.invalid_endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property!.
        /// </summary>
        internal static string opcs_error_request_invalid_property {
            get {
                return ResourceManager.GetString("opcs.error.request.invalid_property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property is not {0} type!.
        /// </summary>
        internal static string opcs_error_request_invalid_property_type {
            get {
                return ResourceManager.GetString("opcs.error.request.invalid_property_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property type is not equal!.
        /// </summary>
        internal static string opcs_error_request_property_type_not_equal {
            get {
                return ResourceManager.GetString("opcs.error.request.property_type_not_equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be equal!.
        /// </summary>
        internal static string opcs_error_request_value_not_equal {
            get {
                return ResourceManager.GetString("opcs.error.request.value_not_equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role not exist!.
        /// </summary>
        internal static string opcs_error_role_not_exist {
            get {
                return ResourceManager.GetString("opcs.error.role.not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier not exist!.
        /// </summary>
        internal static string opcs_error_supplier_not_exist {
            get {
                return ResourceManager.GetString("opcs.error.supplier.not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exist!.
        /// </summary>
        internal static string opcs_error_user_user_exist {
            get {
                return ResourceManager.GetString("opcs.error.user.user_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login success!.
        /// </summary>
        internal static string opcs_info_auth_login_successful {
            get {
                return ResourceManager.GetString("opcs.info.auth.login_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration success!.
        /// </summary>
        internal static string opcs_info_auth_registration_successful {
            get {
                return ResourceManager.GetString("opcs.info.auth.registration_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session refreshed!.
        /// </summary>
        internal static string opcs_info_auth_session_refresh {
            get {
                return ResourceManager.GetString("opcs.info.auth.session_refresh", resourceCulture);
            }
        }
    }
}
